// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP2Xn3DsZHzV0ZXmNnSlPl6hgznHB7wXM',
    appId: '1:301797870925:web:4873f5e2430fcc0e77fb04',
    messagingSenderId: '301797870925',
    projectId: 'chamdx-aecc2',
    authDomain: 'chamdx-aecc2.firebaseapp.com',
    storageBucket: 'chamdx-aecc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsoVMfTZGBSlIi1eoyT6MM8iNSErHsFWk',
    appId: '1:301797870925:android:016e09c2a6f3f4f977fb04',
    messagingSenderId: '301797870925',
    projectId: 'chamdx-aecc2',
    storageBucket: 'chamdx-aecc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8SmawyUqH849PSFGyd2KmglDV2vaanuk',
    appId: '1:301797870925:ios:18f096d4ad1bf0e877fb04',
    messagingSenderId: '301797870925',
    projectId: 'chamdx-aecc2',
    storageBucket: 'chamdx-aecc2.firebasestorage.app',
    iosBundleId: 'com.example.chamdx',
  );
}
